// Generated by CoffeeScript 1.6.2
var Graphite,
  __slice = [].slice;

Graphite = (function() {
  var Series, fname, functions, _fn, _i, _len, _resolve_arg;

  Series = (function() {
    function Series(args) {
      this.series = args;
    }

    Series.prototype.toString = function() {
      return this.series;
    };

    Series.func = function() {
      var args, instance, name;

      name = arguments[0], instance = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      return Graphite.func(name, [instance].concat(args));
    };

    return Series;

  })();

  function Graphite(base, attrs) {
    if (attrs == null) {
      attrs = {};
    }
    this.base = base;
    this.attrs = attrs;
    this.targets = [];
  }

  Graphite.prototype.attr = function(k, v) {
    return this.attrs[k] = v;
  };

  Graphite.prototype.target = function(target) {
    return this.targets.push(typeof target === "function" ? target() : target);
  };

  Graphite.prototype.s = function(string) {
    return Graphite.s(string);
  };

  Graphite.s = function() {
    var series;

    series = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return Object(result) === result ? result : child;
    })(Series, series, function(){});
  };

  Graphite.prototype.render = function() {
    var k, t, v;

    return this.base + '?' + ((function() {
      var _ref, _results;

      _ref = this.attrs;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push("" + k + "=" + v);
      }
      return _results;
    }).call(this)).join('&') + '&' + ((function() {
      var _i, _len, _ref, _results;

      _ref = this.targets;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        _results.push("target=" + t);
      }
      return _results;
    }).call(this)).join('&');
  };

  _resolve_arg = function(arg, result) {
    var a, _i, _len, _results;

    if (arg instanceof Array) {
      _results = [];
      for (_i = 0, _len = arg.length; _i < _len; _i++) {
        a = arg[_i];
        _results.push(_resolve_arg(a, result));
      }
      return _results;
    } else if (typeof arg === "function") {
      return _resolve_arg(arg(), result);
    } else if (arg instanceof Series) {
      return result.push(arg);
    } else if ((arg instanceof String) || typeof arg === "string") {
      return result.push("'" + arg + "'");
    } else {
      return result.push(arg);
    }
  };

  Graphite.func = function() {
    var a, args, flattenedArgs, name, otherArgs, seriesLists, _i, _j, _len, _len1;

    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    flattenedArgs = [];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      a = args[_i];
      _resolve_arg(a, flattenedArgs);
    }
    seriesLists = [];
    otherArgs = [];
    for (_j = 0, _len1 = flattenedArgs.length; _j < _len1; _j++) {
      a = flattenedArgs[_j];
      if (a instanceof Series) {
        seriesLists.push(a);
      } else {
        otherArgs.push(a);
      }
    }
    return this.s("" + name + "(" + (seriesLists.concat(otherArgs).join(',')) + ")");
  };

  functions = ['alias', 'aliasByNode', 'aliasSub', 'alpha', 'areaBetween', 'asPercent', 'averageAbove', 'averageBelow', 'averageSeries', 'averageSeriesWithWildcards', 'cactiStyle', 'color', 'constantLine', 'cumulative', 'currentAbove', 'currentBelow', 'dashed', 'derivative', 'diffSeries', 'divideSeries', 'drawAsInfinite', 'events', 'exclude', 'groupByNode', 'highestAverage', 'highestCurrent', 'highestMax', 'hitcount', 'holtWintersAberration', 'holtWintersConfidenceBands', 'holtWintersForecast', 'integral', 'keepLastValue', 'legendValue', 'limit', 'lineWidth', 'logarithm', 'lowestAverage', 'lowestCurrent', 'maxSeries', 'maximumAbove', 'maximumBelow', 'minSeries', 'minimumAbove', 'mostDeviant', 'movingAverage', 'movingMedian', 'multiplySeries', 'nPercentile', 'nonNegativeDerivative', 'offset', 'randomWalkFunction', 'rangeOfSeries', 'removeAbovePercentile', 'removeAboveValue', 'removeBelowPercentile', 'removeBelowValue', 'scale', 'secondYAxis', 'sinFunction', 'smartSummarize', 'sortByMaxima', 'sortByMinima', 'stacked', 'stdev', 'substr', 'sumSeries', 'sumSeriesWithWildcards', 'summarize', 'threshold', 'timeFunction', 'timeShift'];

  _fn = function(fname) {
    Graphite.prototype[fname] = function() {
      var args;

      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return Graphite.func.apply(Graphite, [fname].concat(__slice.call(args)));
    };
    return Series.prototype[fname] = function() {
      var args;

      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return Series.func.apply(Series, [fname, this].concat(__slice.call(args)));
    };
  };
  for (_i = 0, _len = functions.length; _i < _len; _i++) {
    fname = functions[_i];
    _fn(fname);
  }

  return Graphite;

}).call(this);

/*
//@ sourceMappingURL=graphite.map
*/
