// Generated by CoffeeScript 1.3.1

describe('GraphiteUrl', function() {
  var g;
  g = null;
  beforeEach(function() {
    return g = new GraphiteUrl("http://example.com/");
  });
  it('renders a url', function() {
    var url;
    g.target(function() {
      return g.sumSeries(g.s('series1'), g.s('series2'));
    });
    url = g.render();
    return expect(url).toBe('http://example.com/?&target=sumSeries(series1,series2)');
  });
  it('expands array arguments', function() {
    var url;
    g.target(function() {
      return g.sumSeries([g.s('series1'), g.s('series2')]);
    });
    url = g.render();
    return expect(url).toBe('http://example.com/?&target=sumSeries(series1,series2)');
  });
  it('stringifies string arguments', function() {
    var url;
    g.target(function() {
      return g.alias(g.s('series'), 'my series');
    });
    url = g.render();
    return expect(url).toBe('http://example.com/?&target=alias(series,\'my series\')');
  });
  it('relocates serieslists to the front of arguments', function() {
    var url;
    g.target(function() {
      return g.alias("my series", function() {
        return g.s('series');
      });
    });
    url = g.render();
    return expect(url).toBe('http://example.com/?&target=alias(series,\'my series\')');
  });
  return it('relocates seriesLists to the front that are embedded in other calls', function() {
    var url;
    g.target(function() {
      return g.alias("my sum", function() {
        return g.sumSeries(g.s('series1'), g.s('series2'));
      });
    });
    url = g.render();
    return expect(url).toBe('http://example.com/?&target=alias(sumSeries(series1,series2),\'my sum\')');
  });
});
